In [1]:
import numpy as np
import random

np.random.seed(19)

xn=3

iter=1000
n_elem=10

x0=0.1
r=3.8

q=1
prec=15

x=np.empty((n_elem*iter,1),dtype=np.double)
y=np.empty((n_elem,1),dtype=np.double)

file= open("3logis_data1000_d10_v10.csv","w+")
file2=open("3logis_lab_data1000_d10_v10.csv", "w+")

In [2]:

for i in range (200): #deve ser >3.3*d (onde d são digitos de precisão)
    x1=r*x0*(1-x0)
    x1=round(x1,prec)
    x0=x1


In [3]:
x[0]=x0
for i in range (n_elem*iter-1):
    x1=r*x0*(1-x0)
    x1=round(x1,prec)
    x[i+1]=x1
    x0=x1
print (x)

[[0.93877654]
 [0.21840557]
 [0.64867738]
 ...
 [0.29956616]
 [0.79733985]
 [0.61403826]]


In [4]:
ind=random.sample(range((n_elem*iter)-n_elem-1), iter)


for i in range (iter):
    for j in range (n_elem):
        y[j]=x[ind[i]+j]
        
    
    y_l=y.tolist()
    y_s=','.join(map(str, y_l))
    y_s=y_s.replace('[','').replace(']','')

    file.write(y_s)
    file.write("\n")
    
    yp=float(y[n_elem-1])
    for ii in range (xn):
        yp=r*yp*(1-yp)
        
    s=str(yp*pow(10,q))[0:q]
    print(y,yp,s)
    
    file2.write(s)
    file2.write('\n')
        
    
    



[[0.56334606]
 [0.93475165]
 [0.23176581]
 [0.6765916 ]
 [0.83149855]
 [0.5324131 ]
 [0.94600769]
 [0.19409315]
 [0.59439979]
 [0.91613698]] 0.6402086352907251 6
[[0.52628868]
 [0.94737384]
 [0.18945526]
 [0.58353546]
 [0.92348294]
 [0.26851635]
 [0.74637822]
 [0.71933153]
 [0.76719598]
 [0.67870396]] 0.9440508041389679 9
[[0.8051907 ]
 [0.59606281]
 [0.91493336]
 [0.29575517]
 [0.79147939]
 [0.62715111]
 [0.88856386]
 [0.37626888]
 [0.89182432]
 [0.36660008]] 0.9076199234755452 9
[[0.92767257]
 [0.25496545]
 [0.72184067]
 [0.76298953]
 [0.68717873]
 [0.81686367]
 [0.56847017]
 [0.93218498]
 [0.24022136]
 [0.69355722]] 0.9189663960731018 9
[[0.90420998]
 [0.32913431]
 [0.83905868]
 [0.51314901]
 [0.94934299]
 [0.18274532]
 [0.56752798]
 [0.93267189]
 [0.23862112]
 [0.69038812]] 0.9259960803097653 9
[[0.83490658]
 [0.52378282]
 [0.94785063]
 [0.18783328]
 [0.57969736]
 [0.92586366]
 [0.26083255]
 [0.73263594]
 [0.74434598]
 [0.72312117]] 0.8106623005927399 8
[[0.82025854]
 [0.56025096]


 [0.93759021]] 0.856246638627517 8
[[0.94196498]
 [0.20773444]
 [0.62540721]
 [0.89023752]
 [0.37131577]
 [0.8870734 ]
 [0.38066189]
 [0.89588198]
 [0.35445434]
 [0.86950256]] 0.2408243505108001 2
[[0.18113095]
 [0.56362561]
 [0.93461677]
 [0.2322114 ]
 [0.67749921]
 [0.83027732]
 [0.53548419]
 [0.94521531]
 [0.19677663]
 [0.60061123]] 0.8076179249706859 8
[[0.83131102]
 [0.53288543]
 [0.94589048]
 [0.19449037]
 [0.59532269]
 [0.91547162]
 [0.29405667]
 [0.78883191]
 [0.63298929]
 [0.88279263]] 0.3216335270238037 3
[[0.20816162]
 [0.62635538]
 [0.88933041]
 [0.37400296]
 [0.88967404]
 [0.37298575]
 [0.88869605]
 [0.37587846]
 [0.8914566 ]
 [0.36769457]] 0.9049993680179211 9
[[0.92083982]
 [0.27699661]
 [0.76102406]
 [0.69109247]
 [0.81123794]
 [0.5818976 ]
 [0.92451258]
 [0.26519847]
 [0.74049932]
 [0.73020828]] 0.7741443128451786 7
[[0.67731911]
 [0.83052015]
 [0.53487443]
 [0.94537834]
 [0.19622491]
 [0.59933863]
 [0.91250098]
 [0.30340319]
 [0.80312883]
 [0.60082906]] 0.808383929140

[[0.94885988]
 [0.18439427]
 [0.57149349]
 [0.93057699]
 [0.24549313]
 [0.70385977]
 [0.79207654]
 [0.62582693]
 [0.88983682]
 [0.37250357]] 0.8927481559086623 8
[[0.63413499]
 [0.88162966]
 [0.39656345]
 [0.90934334]
 [0.3132645 ]
 [0.81749345]
 [0.56695206]
 [0.9329662 ]
 [0.23765302]
 [0.68846144]] 0.9298236585923813 9
[[0.43452443]
 [0.93370921]
 [0.23520602]
 [0.68355976]
 [0.82196209]
 [0.55609356]
 [0.93804335]
 [0.2208485 ]
 [0.65388288]
 [0.86001623]] 0.20382154563124766 2
[[0.6597148 ]
 [0.8530665 ]
 [0.47630739]
 [0.94786691]
 [0.18777788]
 [0.57956593]
 [0.9259432 ]
 [0.26057508]
 [0.7321677 ]
 [0.74517301]] 0.6863093656379299 6
[[0.7412485 ]
 [0.72883681]
 [0.75100811]
 [0.71058073]
 [0.78149188]
 [0.64889682]
 [0.865753  ]
 [0.44165403]
 [0.93706384]
 [0.22410576]] 0.4796937776678465 4
[[0.57572793]
 [0.92820807]
 [0.25322384]
 [0.7185858 ]
 [0.76843695]
 [0.6761781 ]
 [0.83205286]
 [0.53101542]
 [0.94634457]
 [0.19295081]] 0.28598836687394996 2
[[0.25147114]
 [0.71528693

 [0.34832231]] 0.9406682766866172 9
[[0.52506018]
 [0.94761355]
 [0.18864001]
 [0.58160884]
 [0.92469199]
 [0.26461951]
 [0.73946489]
 [0.73209495]
 [0.74530135]
 [0.72134354]] 0.8192372228583145 8
[[0.62402612]
 [0.89154658]
 [0.36742684]
 [0.88321255]
 [0.39196292]
 [0.90564636]
 [0.32471391]
 [0.83324419]
 [0.52800359]
 [0.94702004]] 0.9216541792734254 9
[[0.32818968]
 [0.83782862]
 [0.51631294]
 [0.94898877]
 [0.18395451]
 [0.57043793]
 [0.93114629]
 [0.24362893]
 [0.70024072]
 [0.79763389]] 0.33847901389929563 3
[[0.9298289 ]
 [0.24793903]
 [0.70856802]
 [0.78469765]
 [0.64199955]
 [0.87337728]
 [0.42023973]
 [0.92582554]
 [0.26095592]
 [0.73286012]] 0.759574612934855 7
[[0.79589019]
 [0.61730619]
 [0.89770918]
 [0.34894415]
 [0.86329209]
 [0.44847165]
 [0.93991035]
 [0.21461976]
 [0.64052084]
 [0.87496479]] 0.2700326049611657 2
[[0.94878753]
 [0.18464107]
 [0.57208524]
 [0.93025413]
 [0.24654925]
 [0.70589833]
 [0.78890233]
 [0.63283469]
 [0.88294879]
 [0.39273085]] 0.83064754136

In [5]:

file.close()
file2.close()