In [1]:
import numpy as np
import random

np.random.seed(19)

iter=10000
n_elem=2

x0=0.1
r=3.8

q=2
prec=15

x=np.empty((n_elem*iter,1),dtype=np.double)
y=np.empty((n_elem,1),dtype=np.double)

file= open("logis_data10000_d100_v2.csv","w+")
file2=open("logis_lab_data10000_d100_v2.csv", "w+")

In [2]:

for i in range (200): #deve ser >3.3*d (onde d são digitos de precisão)
    x1=r*x0*(1-x0)
    x1=round(x1,prec)
    x0=x1


In [3]:
x[0]=x0
for i in range (n_elem*iter-1):
    x1=r*x0*(1-x0)
    x1=round(x1,prec)
    x[i+1]=x1
    x0=x1
print (x)

[[0.93877654]
 [0.21840557]
 [0.64867738]
 ...
 [0.94063835]
 [0.21218381]
 [0.63521499]]


In [4]:
ind=random.sample(range((n_elem*iter)-n_elem-1), iter)


for i in range (iter):
    for j in range (n_elem):
        y[j]=x[ind[i]+j]
        
    yp=float(x[ind[i]+n_elem])
    
    y_l=y.tolist()
    y_s=','.join(map(str, y_l))
    y_s=y_s.replace('[','').replace(']','')

    file.write(y_s)
    file.write("\n")
    
    s=str(yp*pow(10,q))[0:q]
    print(y,yp,s)
    
    file2.write(s)
    file2.write('\n')
        
    
    



[[0.58382806]
 [0.92329686]] 0.269115133192172 26
[[0.9278258 ]
 [0.25446731]] 0.720912056212322 72
[[0.5362773 ]
 [0.94499904]] 0.197508255843343 19
[[0.90760835]
 [0.31865065]] 0.825027164866934 82
[[0.66031136]
 [0.85234101]] 0.478252075394796 47
[[0.94104595]
 [0.2108182 ]] 0.632220765599099 63
[[0.86878613]
 [0.4331878 ]] 0.933037296100311 93
[[0.90771897]
 [0.31830793]] 0.824554371398984 82
[[0.94532997]
 [0.19638864]] 0.599716549951377 59
[[0.70606156]
 [0.7886468 ]] 0.633395487225641 63
[[0.51701723]
 [0.94889957]] 0.184258858847089 18
[[0.50892774]
 [0.94969712]] 0.181535491292811 18
[[0.94524858]
 [0.19666407]] 0.600351787460743 60
[[0.54245168]
 [0.94315185]] 0.203742469070422 20
[[0.69756023]
 [0.80168583]] 0.604145517309407 60
[[0.93936233]
 [0.21645083]] 0.644479501344386 64
[[0.93375069]
 [0.23506929]] 0.683284522929362 68
[[0.53454002]
 [0.94546655]] 0.195926294514594 19
[[0.80104182]
 [0.60562054]] 0.907608349815981 90
[[0.36029332]
 [0.87583177]] 0.413251836044714 41


 [0.82274631]] 0.554172307835962 55
[[0.90734877]
 [0.31945453]] 0.826132667573543 82
[[0.39046769]
 [0.90441016]] 0.328519212413176 32
[[0.56320472]
 [0.93481962]] 0.23154120274273 23
[[0.33745606]
 [0.84960197]] 0.48555815450135 48
[[0.62181115]
 [0.89361577]] 0.361253189028932 36
[[0.62293618]
 [0.89256944]] 0.36437907919233 36
[[0.66050225]
 [0.85210831]] 0.478875017626891 47
[[0.40629628]
 [0.91663453]] 0.290379545743903 29
[[0.56884583]
 [0.93198896]] 0.240865050611243 24
[[0.94248865]
 [0.20597442]] 0.621486052261419 62
[[0.91527099]
 [0.29469002]] 0.78982169031577 78
[[0.2294863 ]
 [0.67192489]] 0.837678961424319 83
[[0.56554466]
 [0.93367481]] 0.235319403029636 23
[[0.48873743]
 [0.94951799]] 0.182147601009413 18
[[0.38835084]
 [0.90263097]] 0.333975545920496 33
[[0.30232339]
 [0.80151103]] 0.604546165596284 60
[[0.63655809]
 [0.87913717]] 0.403769022382885 40
[[0.26598382]
 [0.74189842]] 0.727643584264435 72
[[0.26970259]
 [0.74845979]] 0.71541737969441 71
[[0.53826366]
 [0.9

 [0.18770655]] 0.57939664704254 57
[[0.689883  ]
 [0.81298889]] 0.577744228105641 57
[[0.70871609]
 [0.78446285]] 0.642507364795497 64
[[0.90593548]
 [0.32382227]] 0.832053342365333 83
[[0.54255749]
 [0.94311767]] 0.203857583629283 20
[[0.78091752]
 [0.65012432]] 0.864358210766261 86
[[0.35702712]
 [0.87232327]] 0.423226458724898 42
[[0.58686624]
 [0.92132617]] 0.275440172777731 27
[[0.94613592]
 [0.19365843]] 0.593388406247174 59
[[0.76996908]
 [0.67304345]] 0.836212667429277 83
[[0.9140822 ]
 [0.29843655]] 0.795614263694396 79
[[0.93106256]
 [0.24390327]] 0.700774959590139 70
[[0.91928767]
 [0.28195182]] 0.769328969050796 76
[[0.18998616]
 [0.5847874 ]] 0.92268216664117 92
[[0.65426637]
 [0.85956718]] 0.45870349630514 45
[[0.83808915]
 [0.51564375]] 0.949070037392494 94
[[0.50540619]
 [0.94988894]] 0.180879786144178 18
[[0.73887482]
 [0.73316751]] 0.743405067463605 74
[[0.90100159]
 [0.33895134]] 0.851440650095138 85
[[0.91782477]
 [0.28660535]] 0.776958349851292 77
[[0.85931896]
 [0

 [0.66172364]] 0.850612767258205 85
[[0.84527418]
 [0.49698582]] 0.949965475986212 94
[[0.71989111]
 [0.76626201]] 0.680597254215532 68
[[0.64537565]
 [0.8696905 ]] 0.430649941953219 43
[[0.93310882]
 [0.23718365]] 0.68752474954086 68
[[0.76731797]
 [0.67845619]] 0.828982876494987 82
[[0.61956242]
 [0.89567835]] 0.355066855745219 35
[[0.858894  ]
 [0.46054136]] 0.944083459100012 94
[[0.19286149]
 [0.59153055]] 0.918164205261335 91
[[0.94998734]
 [0.1805433 ]] 0.562200191448501 56
[[0.82140561]
 [0.55745405]] 0.937456322959277 93
[[0.53629474]
 [0.94499423]] 0.197524515708074 19
[[0.8215771 ]
 [0.55703504]] 0.937638616576162 93
[[0.94795446]
 [0.18747984]] 0.578858360251649 57
[[0.57043793]
 [0.93114629]] 0.243628926644082 24
[[0.89320487]
 [0.36248173]] 0.87813715568154 87
[[0.75331461]
 [0.7061605 ]] 0.78849182294897 78
[[0.21559797]
 [0.64263884]] 0.87268581071751 87
[[0.22217854]
 [0.65669789]] 0.856693933542673 85
[[0.57785061]
 [0.92696927]] 0.257249510985994 25
[[0.76636818]
 [0.

 [0.52857636]] 0.946896888680387 94
[[0.42072975]
 [0.92612167]] 0.259997238971419 25
[[0.82825417]
 [0.54054696]] 0.943752586698974 94
[[0.42712926]
 [0.92982145]] 0.247963380297411 24
[[0.35250306]
 [0.86732968]] 0.437261840496578 43
[[0.88560118]
 [0.38498458]] 0.899731524373435 89
[[0.84895587]
 [0.48727325]] 0.94938451309713 94
[[0.4759    ]
 [0.94779292]] 0.188029697567193 18
[[0.23503659]
 [0.68321869]] 0.822437460870657 82
[[0.84062022]
 [0.5091159 ]] 0.949684221687453 94
[[0.26130335]
 [0.73349085]] 0.742831690917588 74
[[0.70322459]
 [0.79305911]] 0.623642163126151 62
[[0.93288204]
 [0.23792992]] 0.689013233961391 68
[[0.60031413]
 [0.91176089]] 0.305721296811769 30
[[0.91954679]
 [0.28112588]] 0.767957654777793 76
[[0.93163988]
 [0.24201066]] 0.697077698146454 69
[[0.92787297]
 [0.25431393]] 0.720625756654804 72
[[0.25848898]
 [0.72835522]] 0.751844789986002 75
[[0.70804689]
 [0.78552267]] 0.640211866679707 64
[[0.57320592]
 [0.92963539]] 0.248571025862352 24
[[0.5329921 ]
 

 [0.56715775]] 0.932861378656329 93
[[0.82801704]
 [0.54113832]] 0.943569027410143 94
[[0.83705882]
 [0.51828713]] 0.948729207640285 94
[[0.9471052 ]
 [0.19036837]] 0.585687355023406 58
[[0.94943521]
 [0.18243036]] 0.566768200705565 56
[[0.72119664]
 [0.76407377]] 0.68500716585711 68
[[0.87740303]
 [0.40875441]] 0.918362119544443 91
[[0.24954787]
 [0.71164018]] 0.779792052052817 77
[[0.54139679]
 [0.94348796]] 0.202610024017254 20
[[0.92344587]
 [0.26863565]] 0.746588040586214 74
[[0.68629195]
 [0.81812218]] 0.565433459291463 56
[[0.27258048]
 [0.75346537]] 0.705870159009044 70
[[0.44812624]
 [0.93977463]] 0.215073440105649 21
[[0.94852237]
 [0.18554518]] 0.574249038360467 57
[[0.62831519]
 [0.88743381]] 0.379601163952058 37
[[0.63286783]
 [0.88291533]] 0.392828234640145 39
[[0.93503462]
 [0.23083055]] 0.674681667433759 67
[[0.92523769]
 [0.26285705]] 0.736300241330541 73
[[0.88475513]
 [0.38746128]] 0.901873135150156 90
[[0.9215327 ]
 [0.27477869]] 0.75724637223834 75
[[0.89701696]
 [

 [0.56295025]] 0.934941609920303 93
[[0.88862574]
 [0.37608614]] 0.891652353786644 89
[[0.51981329]
 [0.94850825]] 0.185593338773 18
[[0.94373054]
 [0.20179218]] 0.612073970322073 61
[[0.63193753]
 [0.88385145]] 0.390100642283854 39
[[0.94981547]
 [0.18113095]] 0.563625610279926 56
[[0.38738615]
 [0.90180886]] 0.336488644605952 33
[[0.90105718]
 [0.33878192]] 0.851233181698912 85
[[0.69571291]
 [0.80444654]] 0.597786748375105 59
[[0.68947094]
 [0.8135829 ]] 0.576329906039832 57
[[0.56874802]
 [0.9320401 ]] 0.240697149172913 24
[[0.57606058]
 [0.9280162 ]] 0.253848111981665 25
[[0.38872773]
 [0.90295023]] 0.332998215177233 33
[[0.54599856]
 [0.9419597 ]] 0.207752162368761 20
[[0.49677569]
 [0.94996049]] 0.18063510245684 18
[[0.87711865]
 [0.40956979]] 0.918925035503747 91
[[0.68266258]
 [0.82321065]] 0.553032517306891 55
[[0.5433476 ]
 [0.94285975]] 0.204725933782938 20
[[0.71109648]
 [0.78066545]] 0.650662235697117 65
[[0.88368142]
 [0.39059655]] 0.90451735938532 90
[[0.73392652]
 [0.7

 [0.7827869 ]] 0.64611996348356 64
[[0.5207134 ]
 [0.94836963]] 0.186065769697247 18
[[0.56224614]
 [0.93527659]] 0.230030314842467 23
[[0.32517054]
 [0.83385171]] 0.52646353306905 52
[[0.33774031]
 [0.84995281]] 0.484625513308911 48
[[0.80340952]
 [0.60018213]] 0.911861457489695 91
[[0.83584013]
 [0.52140335]] 0.948259207676615 94
[[0.90169859]
 [0.33682533]] 0.848821300336486 84
[[0.86687314]
 [0.43853557]] 0.935644071444336 93
[[0.18648845]
 [0.57649993]] 0.927761487853723 92
[[0.87663194]
 [0.41096386]] 0.919875749857258 91
[[0.37558019]
 [0.8911749 ]] 0.368532350348875 36
[[0.25759398]
 [0.72670943]] 0.754690772294068 75
[[0.69099095]
 [0.81138534]] 0.581548841422011 58
[[0.67466457]
 [0.83407069]] 0.525907739932451 52
[[0.7734226 ]
 [0.66591231]] 0.845397799439965 84
[[0.72340412]
 [0.76034428]] 0.692439250707079 69
[[0.23076843]
 [0.67455457]] 0.834216669297322 83
[[0.21528986]
 [0.64197252]] 0.873406449449075 87
[[0.30507292]
 [0.80561305]] 0.595082526429599 59
[[0.9275587 ]
 [

 [0.87135837]] 0.425953251945477 42
[[0.27823528]
 [0.76311755]] 0.686922788765094 68
[[0.6734218 ]
 [0.83571454]] 0.521723850311442 52
[[0.30269793]
 [0.8020732 ]] 0.603256770195373 60
[[0.93010303]
 [0.24704326]] 0.706848973930987 70
[[0.18759402]
 [0.57912952]] 0.926206375156746 92
[[0.61190675]
 [0.90241214]] 0.33464499226596 33
[[0.67403801]
 [0.83490093]] 0.523797207458053 52
[[0.2460394 ]
 [0.70491525]] 0.790437018844982 79
[[0.68119439]
 [0.82524066]] 0.548030351292577 54
[[0.5599698 ]
 [0.93633377]] 0.226528807439344 22
[[0.77221345]
 [0.66841939]] 0.842212655542383 84
[[0.57052165]
 [0.93110145]] 0.243775860005792 24
[[0.90399246]
 [0.32980234]] 0.83992447298485 83
[[0.84669294]
 [0.49325522]] 0.949827130412657 94
[[0.20071176]
 [0.60962088]] 0.904336397957306 90
[[0.57959824]
 [0.92592365]] 0.260638355699049 26
[[0.71106069]
 [0.78072286]] 0.650539762425944 65
[[0.23326856]
 [0.67964648]] 0.827363136038613 82
[[0.66841425]
 [0.84221923]] 0.504966789275737 50
[[0.70782248]
 [

[[0.94945865]
 [0.18235032]] 0.566574980652536 56
[[0.19216418]
 [0.58990101]] 0.919287672410302 91
[[0.20237314]
 [0.61338935]] 0.901142849608286 90
[[0.94741663]
 [0.18930975]] 0.583191961112748 58
[[0.81619733]
 [0.57007314]] 0.93134106915132 93
[[0.63981808]
 [0.87571343]] 0.413589783743813 41
[[0.90494644]
 [0.32686985]] 0.836098616865535 83
[[0.94951743]
 [0.18214951]] 0.56609004724794 56
[[0.20882547]
 [0.6278261 ]] 0.887909859339548 88
[[0.81391073]
 [0.57554819]] 0.928311387126116 92
[[0.44371398]
 [0.93796116]] 0.221122094411853 22
[[0.94704825]
 [0.19056187]] 0.586142554456008 58
[[0.6572194 ]
 [0.85607182]] 0.468208855574061 46
[[0.81508313]
 [0.57274595]] 0.929890500387988 92
[[0.86429646]
 [0.44569473]] 0.938793562812386 93
[[0.84428321]
 [0.49958246]] 0.94999933751177 94
[[0.92916126]
 [0.25011832]] 0.712724757309427 71
[[0.24330753]
 [0.69961411]] 0.798585981576534 79
[[0.92097053]
 [0.2765785 ]] 0.76031476606646 76
[[0.76449841]
 [0.68415425]] 0.821131404757295 82
[[0.

 [0.57632991]] 0.927860232687012 92
[[0.52184164]
 [0.94818718]] 0.186687346894766 18
[[0.382751  ]
 [0.89776016]] 0.348790056579628 34
[[0.83064754]
 [0.53455437]] 0.945462782199122 94
[[0.94403474]
 [0.20076596]] 0.60974416981012 60
[[0.60376354]
 [0.90908589]] 0.314065198005352 31
[[0.77939932]
 [0.65335687]] 0.860630352848136 86
[[0.64036452]
 [0.87513164]] 0.415249747085839 41
[[0.93467474]
 [0.23201992]] 0.67710936965504 67
[[0.80913026]
 [0.58686624]] 0.921326172941891 92
[[0.7315376 ]
 [0.74628329]] 0.719509254767474 71
[[0.87809116]
 [0.40677889]] 0.916977330780545 91
[[0.6372816]
 [0.8783843]] 0.405936218769011 40
[[0.49303153]
 [0.94981547]] 0.181130950108094 18
[[0.57219489]
 [0.93019401]] 0.24674582549985 24
[[0.94820271]
 [0.18663447]] 0.57684777430954 57
[[0.91210152]
 [0.30465487]] 0.804993066407137 80
[[0.41096386]
 [0.91987575]] 0.28007654779086 28
[[0.23804537]
 [0.68924314]] 0.813910733801599 81
[[0.70950028]
 [0.78321661]] 0.645195742813749 64
[[0.89381158]
 [0.360

 [0.85261578]] 0.477516020888795 47
[[0.70975706]
 [0.7828075 ]] 0.646075681253189 64
[[0.89396764]
 [0.36020008]] 0.875732736622597 87
[[0.93483657]
 [0.23148521]] 0.676019268748298 67
[[0.86160035]
 [0.45313172]] 0.941652785137559 94
[[0.68341151]
 [0.82216882]] 0.555587550842346 55
[[0.52074334]
 [0.94836491]] 0.186081836843742 18
[[0.63551776]
 [0.88021276]] 0.400665383385598 40
[[0.37033161]
 [0.88610721]] 0.383500650303775 38
[[0.78631536]
 [0.63848936]] 0.877118648939033 87
[[0.94879875]
 [0.1846028 ]] 0.571993511560343 57
[[0.77693711]
 [0.65856219]] 0.854460525134612 85
[[0.25366736]
 [0.71941687]] 0.767053693630931 76
[[0.31952871]
 [0.82623443]] 0.545570159243339 54
[[0.83025451]
 [0.53554145]] 0.945199860548104 94
[[0.2535619 ]
 [0.71921939]] 0.767382858740707 76
[[0.58684581]
 [0.92133966]] 0.275396985533235 27
[[0.18120189]
 [0.5637975 ]] 0.934533538164256 93
[[0.94730349]
 [0.18969445]] 0.584099766278699 58
[[0.68361759]
 [0.82188141]] 0.556290961801846 55
[[0.85731271]


 [0.31048564]] 0.813520366569785 81
[[0.72768325]
 [0.75300929]] 0.706747945145659 70
[[0.22813004]
 [0.66912955]] 0.841301743418669 84
[[0.89465747]
 [0.35813282]] 0.87352007541505 87
[[0.71355611]
 [0.77669639]] 0.659068616164162 65
[[0.73941638]
 [0.73218322]] 0.745145611449119 74
[[0.53047639]
 [0.94647052]] 0.192523480481488 19
[[0.23600378]
 [0.68516278]] 0.819716024718232 81
[[0.56471206]
 [0.93408693]] 0.233960457276573 23
[[0.75957461]
 [0.69395988]] 0.807042350916916 80
[[0.53757176]
 [0.94463578]] 0.198736293447963 19
[[0.23322279]
 [0.6795537 ]] 0.827489782819846 82
[[0.88781895]
 [0.37846655]] 0.893872560784325 89
[[0.51742003]
 [0.94884686]] 0.18443867912384 18
[[0.52194436]
 [0.94817009]] 0.186745563694386 18
[[0.76598174]
 [0.68116411]] 0.825282353144431 82
[[0.9352569 ]
 [0.23009545]] 0.673175824441344 67
[[0.92292127]
 [0.27032289]] 0.749544021175408 74
[[0.9087841 ]
 [0.31500312]] 0.819949384138864 81
[[0.40066538]
 [0.91250401]] 0.30339368178705 30
[[0.94920177]
 [0

 [0.21071482]] 0.63199351251114 63
[[0.19749939]
 [0.60227484]] 0.910251457126501 91
[[0.89282431]
 [0.36361844]] 0.879320267294864 87
[[0.882027 ]
 [0.3954104]] 0.90843185995715 90
[[0.26174755]
 [0.73429593]] 0.741400579434806 74
[[0.87679818]
 [0.41048791]] 0.919552828059193 91
[[0.80483949]
 [0.59687697]] 0.914336442453268 91
[[0.87253885]
 [0.42261626]] 0.92724467866064 92
[[0.7800919 ]
 [0.65188439]] 0.862338296811439 86
[[0.86630286]
 [0.44012441]] 0.936376672597105 93
[[0.8966018 ]
 [0.35228665]] 0.867086913721533 86
[[0.63821387]
 [0.87740832]] 0.408739255666717 40
[[0.60460886]
 [0.90841655]] 0.316144505960386 31
[[0.3103695 ]
 [0.81335304]] 0.57687751416694 57
[[0.8409422 ]
 [0.50828198]] 0.949739353388228 94
[[0.92851659]
 [0.25221943]] 0.716698196215326 71
[[0.92696927]
 [0.25724951]] 0.726074360317152 72
[[0.92241378]
 [0.27195306]] 0.752379451306064 75
[[0.6522953 ]
 [0.86186333]] 0.45240872881062 45
[[0.94806852]
 [0.1870915 ]] 0.577935429825297 57
[[0.18167023]
 [0.564

 [0.93534279]] 0.229811274595493 22
[[0.76782956]
 [0.67741585]] 0.830389743959155 83
[[0.18653769]
 [0.57661726]] 0.927693225481261 92
[[0.35506686]
 [0.87017866]] 0.429277492282453 42
[[0.53105396]
 [0.94633548]] 0.192981641986108 19
[[0.88713586]
 [0.38047813]] 0.895715187744129 89
[[0.82183247]
 [0.55641067]] 0.937907776497395 93
[[0.61263072]
 [0.90179442]] 0.336532729578152 33
[[0.79274523]
 [0.62434089]] 0.891249507190697 89
[[0.9466407 ]
 [0.19194591]] 0.589390171919399 58
[[0.93706384]
 [0.22410576]] 0.660752989205376 66
[[0.436769  ]
 [0.93480699]] 0.231582936865485 23
[[0.4775572 ]
 [0.94808602]] 0.187031895430897 18
[[0.6803146 ]
 [0.82644926]] 0.545037355662086 54
[[0.94532609]
 [0.19640176]] 0.599746812134673 59
[[0.70027774]
 [0.79757755]] 0.613500891608398 61
[[0.86177353]
 [0.45265566]] 0.941482352667011 94
[[0.20382155]
 [0.61665763]] 0.898285791718612 89
[[0.64980423]
 [0.86472304]] 0.444513002668315 44
[[0.93706294]
 [0.22410876]] 0.660759292652201 66
[[0.94938123]


[[0.91040151]
 [0.30996829]] 0.812774211836216 81
[[0.901363  ]
 [0.33784943]] 0.850087329923953 85
[[0.36972868]
 [0.88551165]] 0.385246910893579 38
[[0.79406797]
 [0.62139131]] 0.894003766864931 89
[[0.40947133]
 [0.91885733]] 0.283322454108093 28
[[0.75997889]
 [0.6931617 ]] 0.808216512758816 80
[[0.94531588]
 [0.19643631]] 0.599826515851156 59
[[0.7824873 ]
 [0.64676353]] 0.868149777144836 86
[[0.29763619]
 [0.79438577]] 0.620680665925832 62
[[0.51616311]
 [0.94900726]] 0.183891411037925 18
[[0.77644848]
 [0.6595897 ]] 0.85321828726891 85
[[0.42595325]
 [0.9291649 ]] 0.250106454786998 25
[[0.3478804 ]
 [0.86206659]] 0.451849589730378 45
[[0.83378275]
 [0.52663849]] 0.947303485618281 94
[[0.87035958]
 [0.42876836]] 0.930719003630115 93
[[0.63658317]
 [0.87911115]] 0.403844006040741 40
[[0.66606474]
 [0.84520551]] 0.497166001801153 49
[[0.66245598]
 [0.84971061]] 0.485269459445736 48
[[0.68885713]
 [0.81446534]] 0.574223897473289 57
[[0.18079763]
 [0.56281743]] 0.935005087811269 93
[

 [0.69914131]] 0.799302405378138 79
[[0.45762953]
 [0.94317803]] 0.203654303682519 20
[[0.24876549]
 [0.71014863]] 0.782182696023405 78
[[0.91551333]
 [0.29392495]] 0.788625681055632 78
[[0.81608565]
 [0.57034148]] 0.931197891016948 93
[[0.40919019]
 [0.9186636 ]] 0.283939006584802 28
[[0.89188129]
 [0.3664304 ]] 0.882204813768065 88
[[0.8265661 ]
 [0.54474741]] 0.942391144115053 94
[[0.93000706]
 [0.24735693]] 0.707451616061491 70
[[0.89549941]
 [0.35560483]] 0.870770128540545 87
[[0.58382241]
 [0.92330045]] 0.26910355974313 26
[[0.39508792]
 [0.90817513]] 0.316893635521812 31
[[0.18464575]
 [0.57209644]] 0.930247992118274 93
[[0.90574056]
 [0.32442347]] 0.832856956744032 83
[[0.80987108]
 [0.58512368]] 0.92246504430915 92
[[0.56670774]
 [0.93309029]] 0.237244636500573 23
[[0.57107036]
 [0.93080621]] 0.244742822482744 24
[[0.59466301]
 [0.91594788]] 0.292551984070547 29
[[0.8531184 ]
 [0.47616809]] 0.947841752462952 94
[[0.18770358]
 [0.57938959]] 0.926049712240058 92
[[0.73395289]
 [

 [0.38722596]] 0.901671660886717 90
[[0.19381881]
 [0.5937617 ]] 0.916593224378868 91
[[0.56123357]
 [0.93575171]] 0.228457706688451 22
[[0.33251245]
 [0.84340209]] 0.501885011620152 50
[[0.18276049]
 [0.56756455]] 0.932653118014759 93
[[0.28998887]
 [0.78240223]] 0.646946124810432 64
[[0.62433332]
 [0.89125666]] 0.368289266783229 36
[[0.80688873]
 [0.59211337]] 0.917757481662953 91
[[0.58663759]
 [0.92147693]] 0.274957355378977 27
[[0.65155846]
 [0.86271412]] 0.450066172682365 45
[[0.28528339]
 [0.77480776]] 0.663026641507415 66
[[0.85086169]
 [0.48220508]] 0.948796695543521 94
[[0.93564407]
 [0.22881412]] 0.670541237384849 67
[[0.5794666 ]
 [0.92600322]] 0.26038076094219 26
[[0.94634485]
 [0.19294983]] 0.591736730354177 59
[[0.67093593]
 [0.83896745]] 0.513384051308547 51
[[0.69981971]
 [0.79827392]] 0.611924148995376 61
[[0.89361577]
 [0.36125319]] 0.876847425292363 87
[[0.41244908]
 [0.92087238]] 0.276892481384384 27
[[0.77169688]
 [0.66948707]] 0.840841706005389 84
[[0.83395424]
 

 [0.92057013]] 0.277858904271069 27
[[0.83577273]
 [0.52157535]] 0.94823111565606 94
[[0.94969046]
 [0.18155825]] 0.564660447748339 56
[[0.83569255]
 [0.52177995]] 0.948197408170999 94
[[0.47139661]
 [0.94689102]] 0.191095994977229 19
[[0.47453588]
 [0.947536  ]] 0.188903816432308 18
[[0.94920663]
 [0.18321092]] 0.568649782998469 56
[[0.87225515]
 [0.4234192 ]] 0.927714447349595 92
[[0.94272359]
 [0.20518412]] 0.619717658779615 61
[[0.91761907]
 [0.2872584 ]] 0.778015839935012 77
[[0.52181638]
 [0.94819137]] 0.186673073206563 18
[[0.26624055]
 [0.74235478]] 0.726803819396996 72
[[0.89202717]
 [0.36599585]] 0.881762978643767 88
[[0.25261177]
 [0.71743643]] 0.770341310072469 77
[[0.21027179]
 [0.63101875]] 0.88476952818653 88
[[0.70573795]
 [0.78915321]] 0.632283596256864 63
[[0.52811215]
 [0.94699689]] 0.190736375836754 19
[[0.91595739]
 [0.29252191]] 0.786420806929469 78
[[0.67679459]
 [0.83122596]] 0.533099585110627 53
[[0.55153436]
 [0.939908  ]] 0.21462762016391 21
[[0.60124675]
 [0

 [0.79460739]] 0.620184653185643 62
[[0.33981828]
 [0.8524989 ]] 0.477829189618829 47
[[0.70684414]
 [0.78741891]] 0.636083413595366 63
[[0.5932693 ]
 [0.91694319]] 0.289401841491807 28
[[0.86876085]
 [0.43325865]] 0.933073251810153 93
[[0.83101791]
 [0.53362314]] 0.945704041458569 94
[[0.1856483 ]
 [0.57449542]] 0.928911640642639 92
[[0.88100455]
 [0.39837503]] 0.910754985910122 91
[[0.93452994]
 [0.23249819]] 0.678082570912104 67
[[0.91670952]
 [0.29014207]] 0.782646664732817 78
[[0.90032654]
 [0.34100693]] 0.853940569034833 85
[[0.85702587]
 [0.4656236 ]] 0.945509399012837 94
[[0.77979205]
 [0.65252235]] 0.861600345714521 86
[[0.5134657 ]
 [0.94931096]] 0.182854696545136 18
[[0.23397777]
 [0.68108226]] 0.825395023744843 82
[[0.26927157]
 [0.74770468]] 0.716841088148209 71
[[0.44717394]
 [0.93939575]] 0.216339235763344 21
[[0.39356323]
 [0.90695061]] 0.320686561350419 32
[[0.76908942]
 [0.67484535]] 0.833830589724732 83
[[0.65561087]
 [0.85798397]] 0.463020409467074 46
[[0.56482473]


 [0.53393094]] 0.945625027894437 94
[[0.58977928]
 [0.91937079]] 0.281686936542186 28
[[0.27130469]
 [0.75125413]] 0.710111184138839 71
[[0.48504454]
 [0.94915007]] 0.183404016085472 18
[[0.1810036 ]
 [0.56331692]] 0.934765677541874 93
[[0.38996707]
 [0.90399246]] 0.329802338584353 32
[[0.63419638]
 [0.88156706]] 0.396744988035752 39
[[0.787499  ]
 [0.63590843]] 0.879809819325317 87
[[0.34248166]
 [0.8557143 ]] 0.469175880133996 46
[[0.92155046]
 [0.27472179]] 0.757148973100427 75
[[0.6924169]
 [0.8093078]] 0.586449001607465 58
[[0.92324896]
 [0.26926919]] 0.747700520553569 74
[[0.93275806]
 [0.23833777]] 0.689824934111366 68
[[0.63697989]
 [0.87869874]] 0.405031616332362 40
[[0.74700635]
 [0.71815389]] 0.769153749189317 76
[[0.29622322]
 [0.7922051 ]] 0.625541491931617 62
[[0.85612125]
 [0.46807509]] 0.946127039684566 94
[[0.26686031]
 [0.74345437]] 0.724773889553446 72
[[0.26318261]
 [0.73688658]] 0.736762035149905 73
[[0.78851361]
 [0.6336876 ]] 0.882084972615972 88
[[0.82894795]
 [

[[0.94691096]
 [0.19102826]] 0.587238567564009 58
[[0.71767714]
 [0.76994332]] 0.673096291298884 67
[[0.36525813]
 [0.88100958]] 0.398360448212769 39
[[0.94095484]
 [0.21112355]] 0.632891507493242 63
[[0.46830554]
 [0.94618275]] 0.193499617414865 19
[[0.65362453]
 [0.86031811]] 0.456649265231672 45
[[0.39114805]
 [0.90497476]] 0.326782681074346 32
[[0.83964153]
 [0.5116458 ]] 0.949484626729456 94
[[0.94606927]
 [0.19388438]] 0.593914260784352 59
[[0.93309657]
 [0.23722396]] 0.6876052636254 68
[[0.78284025]
 [0.6460053 ]] 0.868993317928172 86
[[0.76577941]
 [0.68157295]] 0.824718799629131 82
[[0.94037955]
 [0.21305025]] 0.637107386644366 63
[[0.80397635]
 [0.59887383]] 0.912851070673553 91
[[0.35572314]
 [0.87089991]] 0.427246363208116 42
[[0.7298582]
 [0.7492278]] 0.713964917347252 71
[[0.81373623]
 [0.5759644 ]] 0.928071760052084 92
[[0.41050136]
 [0.91956197]] 0.281077446894396 28
[[0.35979665]
 [0.87530347]] 0.414759746569743 41
[[0.24267859]
 [0.69838562]] 0.800443951769375 80
[[0.

 [0.61648398]] 0.898439637203701 89
[[0.90853328]
 [0.31578211]] 0.821042328813963 82
[[0.47034742]
 [0.94665875]] 0.191884637886822 19
[[0.67508176]
 [0.83351624]] 0.52731429578673 52
[[0.84504824]
 [0.4975785 ]] 0.949977718136657 94
[[0.23531747]
 [0.683784  ]] 0.821649074942463 82
[[0.8843572 ]
 [0.38862426]] 0.90286269344903 90
[[0.18292554]
 [0.56796238]] 0.932448235045366 93
[[0.29868443]
 [0.79599375]] 0.617073256196226 61
[[0.83853654]
 [0.51449343]] 0.949201773534176 94
[[0.18069228]
 [0.56256181]] 0.935126875858983 93
[[0.73272085]
 [0.74419582]] 0.723399922728925 72
[[0.93896377]
 [0.21778107]] 0.647339407175925 64
[[0.86262716]
 [0.45030586]] 0.940615872409541 94
[[0.87562078]
 [0.4138543 ]] 0.921799889048153 92
[[0.68482442]
 [0.82019175]] 0.560413532207396 56
[[0.84677782]
 [0.49303153]] 0.94981547383107 94
[[0.22237125]
 [0.65710465]] 0.856208884621963 85
[[0.56250669]
 [0.93515307]] 0.23043885408655 23
[[0.28466781]
 [0.77380178]] 0.665123825053827 66
[[0.93404875]
 [0.

[[0.94289844]
 [0.20459569]] 0.618397926632606 61
[[0.92579352]
 [0.26105952]] 0.733048302142313 73
[[0.93888884]
 [0.21803103]] 0.647875300892225 64
[[0.78655731]
 [0.63796266]] 0.877671955358851 87
[[0.63298929]
 [0.88279263]] 0.393185248964922 39
[[0.84047527]
 [0.50949104]] 0.949657696863407 94
[[0.31598983]
 [0.82133298]] 0.557631442098705 55
[[0.5699955 ]
 [0.93138239]] 0.24285507362646 24
[[0.72160209]
 [0.76339155]] 0.686374582096137 68
[[0.85068776]
 [0.48266876]] 0.948858586657725 94
[[0.18424469]
 [0.57113461]] 0.930771494850122 93
[[0.94989338]
 [0.18086461]] 0.562979895630818 56
[[0.53336696]
 [0.94576925]] 0.194901135113254 19
[[0.75673193]
 [0.69953712]] 0.798702759121646 79
[[0.89561192]
 [0.35526658]] 0.870398500326842 87
[[0.5862056 ]
 [0.92176066]] 0.274048200387283 27
[[0.19449129]
 [0.59532483]] 0.915470073100196 91
[[0.70944943]
 [0.78329756]] 0.645021465217212 64
[[0.25133167]
 [0.71502343]] 0.774306715163087 77
[[0.73440269]
 [0.74121044]] 0.72890658538427 72
[[

[[0.94575514]
 [0.19494894]] 0.59638664006022 59
[[0.80170872]
 [0.60409301]] 0.908825650365271 90
[[0.81500941]
 [0.57292247]] 0.929792790880602 92
[[0.23473921]
 [0.68261951]] 0.823270436234196 82
[[0.88514692]
 [0.38631504]] 0.900887770371684 90
[[0.55403609]
 [0.93890438]] 0.217979176225324 21
[[0.93502418]
 [0.23086507]] 0.67475227648163 67
[[0.20253154]
 [0.61374756]] 0.90083367370036 90
[[0.20518412]
 [0.61971766]] 0.895537192270045 89
[[0.94164004]
 [0.20882547]] 0.627826095536549 62
[[0.92865346]
 [0.25177361]] 0.715857908470288 71
[[0.74481457]
 [0.72225014]] 0.762298522227499 76
[[0.64834181]
 [0.86637989]] 0.439909944546588 43
[[0.59138306]
 [0.91826672]] 0.285201209688109 28
[[0.1820425 ]
 [0.56583151]] 0.933531606206249 93
[[0.88294879]
 [0.39273085]] 0.906274651642638 90
[[0.52045196]
 [0.94841053]] 0.185926401436388 18
[[0.56140047]
 [0.93567393]] 0.228715246768732 22
[[0.27205692]
 [0.75255942]] 0.707612207200371 70
[[0.92371483]
 [0.26776983]] 0.745062757553531 74
[[0

 [0.82736314]] 0.542766833219265 54
[[0.86364381]
 [0.44750008]] 0.93952628246219 93
[[0.93677604]
 [0.22506144]] 0.662753391609809 66
[[0.92158578]
 [0.27460863]] 0.756955169039197 75
[[0.59537458]
 [0.91543402]] 0.294175375515539 29
[[0.94116775]
 [0.21040985]] 0.631322670318543 63
[[0.49382249]
 [0.94985499]] 0.180995869268086 18
[[0.63779924]
 [0.87784321]] 0.407491135346344 40
[[0.33993048]
 [0.85263544]] 0.477463334458436 47
[[0.61629957]
 [0.89860276]] 0.346240195633088 34
[[0.18530209]
 [0.57366786]] 0.929377576298083 92
[[0.94567508]
 [0.19522014]] 0.597015092074067 59
[[0.30708969]
 [0.80858532]] 0.588145378426546 58
[[0.59021652]
 [0.91907172]] 0.282639797326647 28
[[0.5016213 ]
 [0.94999001]] 0.180534160891159 18
[[0.5716627 ]
 [0.93048494]] 0.245794333248097 24
[[0.42927749]
 [0.93099364]] 0.24412902536391 24
[[0.50841279]
 [0.94973106]] 0.181419516606916 18
[[0.82953707]
 [0.53734022]] 0.944701690984336 94
[[0.18773603]
 [0.5794666 ]] 0.926003224307606 92
[[0.8303073 ]
 [

 [0.24112211]] 0.695332501582185 69
[[0.82717693]
 [0.54322999]] 0.942898439462636 94
[[0.8265765]
 [0.5447216]] 0.942399918270818 94
[[0.829676 ]
 [0.5369922]] 0.944799994211707 94
[[0.20082489]
 [0.60987817]] 0.904121793668846 90
[[0.79489188]
 [0.61954736]] 0.895692027561653 89
[[0.24853479]
 [0.70970794]] 0.782885802175398 78
[[0.27252299]
 [0.75336599]] 0.706061562541217 70
[[0.7519184 ]
 [0.70884105]] 0.784264584221936 78
[[0.6107058 ]
 [0.90342806]] 0.331534052455494 33
[[0.61330708]
 [0.90121372]] 0.338304692972918 33
[[0.38971094]
 [0.90377803]] 0.330460552869232 33
[[0.78297016]
 [0.64572598]] 0.869302963892094 86
[[0.74658804]
 [0.71893849]] 0.76785057066823 76
[[0.54231628]
 [0.94319546]] 0.203595569969534 20
[[0.79131959]
 [0.62750501]] 0.88822139281074 88
[[0.2634385]
 [0.7373469]] 0.735932509666679 73
[[0.89814467]
 [0.34762713]] 0.861773531909708 86
[[0.9271038 ]
 [0.25681291]] 0.725268148146618 72
[[0.89222969]
 [0.36539232]] 0.88114693362914 88
[[0.88175744]
 [0.39619

[[0.46937244]
 [0.94643542]] 0.192642577141739 19
[[0.2416161 ]
 [0.69630348]] 0.803566786539874 80
[[0.84174214]
 [0.50620677]] 0.949853608831245 94
[[0.7521051 ]
 [0.70848346]] 0.784831652452957 78
[[0.85875999]
 [0.46090682]] 0.944192547914726 94
[[0.18144805]
 [0.56439368]] 0.934243124851768 93
[[0.19915515]
 [0.60607103]] 0.907245959306477 90
[[0.78741891]
 [0.63608341]] 0.879628957268084 87
[[0.49007672]
 [0.94962581]] 0.181779202074991 18
[[0.90553314]
 [0.3250629 ]] 0.833708646198982 83
[[0.32128134]
 [0.82862664]] 0.539617221506079 53
[[0.4074956 ]
 [0.91748316]] 0.287689696896002 28
[[0.94804678]
 [0.18716553]] 0.578111449498449 57
[[0.62902065]
 [0.88674395]] 0.38163064816102 38
[[0.87955569]
 [0.4025624 ]] 0.9139224771154 91
[[0.23034465]
 [0.67368677]] 0.835365041131011 83
[[0.86211346]
 [0.45172061]] 0.941142583155498 94
[[0.9312122 ]
 [0.24341294]] 0.699819710573528 69
[[0.64926812]
 [0.86533231]] 0.442822762554625 44
[[0.80608835]
 [0.59397769]] 0.9164391346193 91
[[0.7

 [0.94480354]] 0.198169289304101 19
[[0.24352576]
 [0.70003967]] 0.797939694130195 79
[[0.53269572]
 [0.94593776]] 0.194330145553324 19
[[0.91456166]
 [0.2969268 ]] 0.793292843734168 79
[[0.18116691]
 [0.56371276]] 0.934574601216166 93
[[0.5970079 ]
 [0.91423998]] 0.297939920890197 29
[[0.61192415]
 [0.90239734]] 0.334690239208314 33
[[0.93408168]
 [0.23397777]] 0.681082255411847 68
[[0.55944641]
 [0.93657127]] 0.225740984521702 22
[[0.33030918]
 [0.84057909]] 0.509222349327606 50
[[0.65008954]
 [0.86439789]] 0.445413865691241 44
[[0.89375611]
 [0.36083329]] 0.876403983178527 87
[[0.92703217]
 [0.25704539]] 0.725697615271439 72
[[0.20619966]
 [0.62198917]] 0.89345084384614 89
[[0.7521333 ]
 [0.70842944]] 0.784917246503085 78
[[0.73083807]
 [0.74751239]] 0.717202945688249 71
[[0.25228262]
 [0.71681718]] 0.771363187266879 77
[[0.52831858]
 [0.94695262]] 0.19088674806023 19
[[0.52024846]
 [0.948442  ]] 0.185819139844405 18
[[0.25699163]
 [0.72559835]] 0.756600465188224 75
[[0.18559334]
 [

 [0.56210969]] 0.93534106954776 93
[[0.1928675]
 [0.5915446]] 0.91815443082486 91
[[0.23013347]
 [0.67325381]] 0.835935851228742 83
[[0.47809746]
 [0.94817706]] 0.18672182850792 18
[[0.54998173]
 [0.94050694]] 0.212623810271288 21
[[0.56748421]
 [0.93269435]] 0.238547279444281 23
[[0.9284431 ]
 [0.25245872]] 0.717148601673852 71
[[0.67785166]
 [0.8298014 ]] 0.536677946836623 53
[[0.23066921]
 [0.67435153]] 0.834485873113777 83
[[0.94123693]
 [0.21017788]] 0.630811920321469 63
[[0.1840786 ]
 [0.57073594]] 0.930986421141248 93
[[0.76843457]
 [0.67618296]] 0.83204635143283 83
[[0.89848162]
 [0.34660712]] 0.860588371416039 86
[[0.86753908]
 [0.4366771 ]] 0.934762799623061 93
[[0.80214199]
 [0.60309884]] 0.909608391806159 90
[[0.47201206]
 [0.94702337]] 0.190646420282505 19
[[0.83330826]
 [0.5278413 ]] 0.947054475205973 94
[[0.68035633]
 [0.82639206]] 0.545179258408245 54
[[0.68099553]
 [0.82551435]] 0.547353544933537 54
[[0.9347628 ]
 [0.23172897]] 0.676516488269169 67
[[0.66749993]
 [0.84

In [5]:

file.close()
file2.close()